2020-10-29 18:48:20,039 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Work/microblog/app/__init__.py:44]
2020-11-04 09:59:12,485 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Work/microblog/app/__init__.py:44]
2020-11-13 17:53:39,231 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Work/microblog/app/__init__.py:44]
2020-11-13 17:54:20,973 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Work/microblog/app/__init__.py:44]
2020-11-13 17:54:38,956 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Work/microblog/app/__init__.py:44]
2020-11-26 21:58:50,507 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Work/microblog/app/__init__.py:44]
2021-03-14 14:45:27,512 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 14:48:02,085 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 14:48:06,565 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 14:49:03,298 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 22:40:21,152 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 23:09:05,156 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 23:10:32,320 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 23:17:05,200 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 23:18:20,251 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 23:18:42,174 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 23:19:13,600 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 23:21:59,931 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 23:25:44,032 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 23:26:50,088 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 23:27:49,946 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-03-14 23:28:36,470 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-12-21 13:48:25,000 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-12-25 14:13:14,220 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-12-25 14:13:47,138 INFO: Microblog startup [in /Users/vaibhavx/Documents/Python_Projects/microblog/app/__init__.py:44]
2021-12-25 14:14:56,121 ERROR: Exception on /user/dodo [GET] [in /Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/app/routes.py", line 71, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/app/templates/user.html", line 25, in block "content"
    {{ form.submit(value+'Unfollow') }}
jinja2.exceptions.UndefinedError: 'value' is undefined
2021-12-25 14:15:14,526 ERROR: Exception on /user/dodo [GET] [in /Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/app/routes.py", line 71, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/vaibhavx/Documents/Python_Projects/microblog/app/templates/user.html", line 25, in block "content"
    {{ form.submit(value+'Unfollow') }}
jinja2.exceptions.UndefinedError: 'value' is undefined
